### ISSUE TITLE
Failed to download geckodriver

### ISSUE THREAD

**Issue by quarckster** [leonidessaguisagjr/webdriverdownloader#2]
Sometimes `webdriverdownloader` fails to download geckodriver inside travis ci:
```
RuntimeError: Error, unable to get info for gecko driver v0.20.1 release. Status code: 403
```
It can fail on different python versions. Here https://travis-ci.org/RedHatQE/widgetastic.core/builds/436013142 you can see how it failed on python 2.7 and 3.6. On the other side usual `wget` does the job  without issues https://travis-ci.org/RedHatQE/widgetastic.core/builds/436020614. But it requires to write bash script inside `.travis.yml`.

**Comment by leonidessaguisagjr** [comment]
Fixed download issue by adding code to fallback to scraping the webpage if the api call fails.  Fix in 6ff6c84311ac9e59144ad584405283cb9604fa60.
